AWSTemplateFormatVersion: 2010-09-09
Description: Create Mapping For AMI ID refered By Region 

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: cfn-key-1
    Description: Select KeyPair, Using Parameter as a String

  EnvironMentName:
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod
  
  InstanceType:
    Type: String 
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium

  AvailabilityZone:
    Type: String
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-2b
      - us-east-2c

Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironMentName,prod]


Resources: 
  MyVMInstanceOne:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-035b3c7efe6d061d5
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install ruby
          sudo yum -y install wget
          sudo wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          sudo chmod +x ./install
          sudo ./install auto
          sudo service codedeploy-agent start

  MyVMInstanceTwo:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-035b3c7efe6d061d5
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroups:
        - !Ref MySecurityGroup
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo yum -y update
          sudo yum -y install ruby
          sudo yum -y install wget
          sudo wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install
          sudo chmod +x ./install
          sudo ./install auto
          sudo service codedeploy-agent start


  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open 8080 and 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0

